name: inventrack
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.2
  intl: ^0.18.1 
  geolocator: ^12.0.0 
  google_maps_flutter: ^2.6.1
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  file_picker: ^8.1.2
  csv: ^6.0.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true

